# 👨🏽‍💻 Ejercicios NumPy 01

## 🧮 Ejercicio 01

*Dadas las siguientes matrices:*

$$
A = \begin{bmatrix}
2 & 8 & -3 \\
3 & -1 & 0 \\
-1 & 1 & 2
\end{bmatrix}
B = \begin{bmatrix}
4 & 0 \\
3 & 5 \\
1 & -4
\end{bmatrix}
C = \begin{bmatrix}
2 & 5 & 3 \\
1 & -2 & 0
\end{bmatrix}
D = \begin{bmatrix}
8 & 3 & 0 \\
7 & -1 & 3 \\
0 & -1 & 0
\end{bmatrix}
$$

> Efectúe la siguiente operación algebraica:

$$
U = (6B) \cdot C + A^T
$$

In [7]:
# Importar numpy:
import numpy as np

# Definir las matrices:
A = np.array([[2, 8, -3], [3, -1, 0], [-1, 1, 2]])
B = np.array([[4, 0], [3, 5], [1, -4]])
C = np.array([[2, 5, 3], [1, -2, 0]])
D = np.array([[8, 3, 0], [7, -1, 3], [0, -1, 0]])

# Efectuar la operación algebraica:
U = (6 * B) @ C + A.T
print(U)

[[ 50 123  71]
 [ 74  29  55]
 [-15  78  20]]


## 🔢 Ejercicio 02

*Considerando la siguiente matriz A:*
$$
A = \begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{bmatrix}
$$

> Resolver:
> 1. La matriz A multiplicarla por una matriz B de «1»s de orden 3x4.
> 2. Generar un vector desde el número 5 hasta el número 14 con pasos de 3 en 3.
> 3. Multiplicar el vector por el resultado de la multiplicación de las dos matrices.

In [8]:
# 1. La matriz A multiplicarla por una matriz B de «1»s de orden 3x4.
A = np.array([[1,2,3], [4,5,6], [7,8,9]])
B = np.ones((3,4), dtype = int)
C = A @ B
print(C)

[[ 6  6  6  6]
 [15 15 15 15]
 [24 24 24 24]]


In [9]:
# 2. Generar un vector desde el número 5 hasta el número 14 con pasos de 3 en 3.
v = np.arange(5, 15, 3, dtype = int)
print(v)

[ 5  8 11 14]


In [10]:
# 3. Multiplicar el vector por el resultado de la multiplicación de las dos matrices.
R = v @ C
print(R)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)

*El error anterior se debe a que el numero de columnas de la primer matriz 🚨NO🚨 es igual al numero de filas de la segunda matriz.*
> 👨🏽‍🏫 **Broadcasting**: Se refiere a cómo NumPy trata los arreglos con diferentes dimensiones durante las operaciones aritméticas. Sujeto a ciertas restricciones, el arreglo con la forma más pequeña se «transmite» a la forma del más grande, de modo que se puedan aplicar las operaciones.

*Luis Felipe Renovato Ávila*

*19051186*

*Ciencia de Datos (19:00 - 20:00)*