# 👨🏽‍💻 Ejercicios NumPy 05

In [1]:
import numpy as np

De la siguiente matriz:

$$
A = \begin{bmatrix}
53 & 37 & 30 \\
64 & 85 & 69 \\
58 & 98 & 21 \\
24 & 48 & 89
\end{bmatrix}
$$

In [2]:
A = np.array([[53, 37, 30], [64, 85, 69], [58, 98, 21], [24, 48, 89]])
print("A = \n", A)

A = 
 [[53 37 30]
 [64 85 69]
 [58 98 21]
 [24 48 89]]


In [3]:
# a) Muestre el renglón 2.
A[1]

array([64, 85, 69])

In [4]:
# b) Ubique el valor de la posición del segundo renglón y segunda columna.
A[1, 1]

85

In [5]:
# c) Muestre la intersección de los dos primeros rengloes y dos primeras columnas.
A[0:2, 0:2]

array([[53, 37],
       [64, 85]])

In [6]:
# d) Muestre la intersección de los dos últimos renglones y dos últimas columnas.
A[2:4, 1:3]

array([[98, 21],
       [48, 89]])

In [7]:
# e) Muestre solamente la segunda columna.
A[:, 1]

array([37, 85, 98, 48])

In [8]:
# f) Genere un arreglo vector de 10 elementos, y realice: sumatoria, producto, máximo, mínimo, desviación estándar, varianza, seno, raíz cuadrada y logaritmo.
v = np.random.randint(0, 100, 10)
print("v = ", v)
print("sumatoria = ", v.sum())
print("producto = ", v.prod())
print("máximo = ", v.max())
print("mínimo = ", v.min())
print("desviación estándar = ", v.std())
print("varianza = ", v.var())
print("seno = ", np.sin(v))
print("raíz cuadrada = ", np.sqrt(v))
print("logaritmo = ", np.log(v))

v =  [81 51 14 68 55 99 81 94 46 17]
sumatoria =  606
producto =  -1217622496
máximo =  99
mínimo =  14
desviación estándar =  28.082734909548964
varianza =  788.64
seno =  [-0.62988799  0.67022918  0.99060736 -0.89792768 -0.99975517 -0.99920683
 -0.62988799 -0.24525199  0.90178835 -0.96139749]
raíz cuadrada =  [9.         7.14142843 3.74165739 8.24621125 7.41619849 9.94987437
 9.         9.69535971 6.78232998 4.12310563]
logaritmo =  [4.39444915 3.93182563 2.63905733 4.21950771 4.00733319 4.59511985
 4.39444915 4.54329478 3.8286414  2.83321334]


In [9]:
# g) De la matriz, genere la suma de los renglones y la suma de las columnas.
print("Suma de los renglones =\t", A.sum(axis=0))
print("Suma de las columnas =\t", A.sum(axis=1))

Suma de los renglones =	 [199 268 209]
Suma de las columnas =	 [120 218 177 161]
