# 👨🏽‍💻 Ejercicios NumPy 02

### a. Genere una matriz de identidad de orden 3 x 3, llamada «A».

In [ ]:
A = np.eye(3)
print(A)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### b. Genere un vector con 3 valores aleatorios de distribución Gaussiana, llamado «v».

In [ ]:
v = np.random.randn(3)
print(v)

[ 0.24196227 -1.91328024 -1.72491783]


### c. Multiplicar vector «v» por matriz «A».

In [ ]:
v @ A

array([ 0.24196227, -1.91328024, -1.72491783])

### d. Genere una matriz de «unos» de orden 3 x 4, llamada «C».

In [ ]:
C = np.ones((3,4), dtype = int)
print(C)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


### e. Genere una matriz de orden 4 x 3 con valores aleatorios entre 1 y 50, llamada «D».

(Del 1 al 50, sin incluir el 50).

In [ ]:
D = np.random.randint(1, 50, (4,3))
print(D)

[[18  4 25]
 [14  9 26]
 [ 2 20 28]
 [47  7 44]]


### f. Haga la siguiente operación:
$$
(2A * C) * D + A^T
$$

In [ ]:
((2*A @ C) @ D) + A.T

array([[163.,  80., 246.],
       [162.,  81., 246.],
       [162.,  80., 247.]])