# 👨🏽‍💻 Ejercicios NumPy 04

In [ ]:
import numpy as np

### a. Genere una matriz aleatoria de orden 4 x 3, llamada «A».

In [48]:
np.random.seed(42)
A = np.random.rand(4, 3)
print(A)

[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]
 [0.70807258 0.02058449 0.96990985]]


### b. Genere un vector de 12 elementos aleatorios, llamado «B».

In [49]:
np.random.seed(42)
B = np.random.randint(0, 20, 12)
print(B)

[ 6 19 14 10  7  6 18 10 10  3  7  2]


### c. Modifique los valores de los indices 7, 8 de ese vector (B).

In [50]:
print(B[7])
print(B[8])

10
10


In [51]:
B[7] = 100
B[8] = 200
print(B[7])
print(B[8])

100
200


In [52]:
print(B)

[  6  19  14  10   7   6  18 100 200   3   7   2]


### d. Redimensione el valor B de tal manera que genere una matriz llamada C, y realice...

In [54]:
C = B.reshape(4, 3)
print(C)

[[  6  19  14]
 [ 10   7   6]
 [ 18 100 200]
 [  3   7   2]]


### e. `D = A + C`.

In [55]:
D = A + C
print(D)

[[  6.37454012  19.95071431  14.73199394]
 [ 10.59865848   7.15601864   6.15599452]
 [ 18.05808361 100.86617615 200.60111501]
 [  3.70807258   7.02058449   2.96990985]]


### f. Obtenga el valor max, min, la sumatoria, el promedio de la matriz resultante.

In [63]:
print("Max:", np.max(D))
print("Min:", np.min(D))
print("Sum:", np.sum(D))
print("Avg:", np.mean(D))

Max: 200.60111501174322
Min: 2.969909852161994
Sum: 398.19186170598454
Avg: 33.18265514216538


### g. Obtenga el índice de en dónde se encuentra el valor max y min.

In [67]:
print("Max:", np.argmax(D))
print("Min:", np.argmin(D))

Max: 8
Min: 11
