# 👨🏽‍💻 Ejercicios NumPy 03

### a. Genere un vector arreglo aleatorio de valores entre 10 a 50 (incluyendo el 50), de 12 elementos llamado «A».

In [ ]:
np.random.seed(42)
A = np.random.randint(10, 51, 12)

In [ ]:
print(A)

[48 38 24 17 30 48 28 32 20 20 33 45]


### b. Redimensione ese vector a una matriz de orden 4 x 3 llamada «B».

In [ ]:
B = A.reshape(4, 3)

In [ ]:
print(B)

[[48 38 24]
 [17 30 48]
 [28 32 20]
 [20 33 45]]


### c. Multiplicar vector arreglo con distribución de Gauss orden 1 x 4 por matriz «B».

In [ ]:
# Vector arreglo con distribución Gaussiana Normal:
np.random.seed(42)
C = np.random.randn(1, 4)
print(C)

[[ 0.49671415 -0.1382643   0.64768854  1.52302986]]


In [ ]:
D = C @ B
print(D)

[[70.08766242 85.71322726 86.77456752]]


### d. El vector resultante multiplica a una matriz de «unos» de orden 3 x 3.

In [ ]:
# Matriz de unos:
E = np.ones((3, 3), dtype=int)
print(E)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
np.random.seed(42)
F = D @ E
print(F)

[[242.5754572 242.5754572 242.5754572]]
