In [1]:
import numpy as np

# 📅 2023-11-07

## 📜 Listas

In [2]:
# Creación de una lista.
my_list = [1, 2, 3, 4]
print(my_list)

[1, 2, 3, 4]


In [3]:
# Multiplicación de una lista por un escalar. El resultado es una lista con los elementos repetidos.
print(my_list * 2)

[1, 2, 3, 4, 1, 2, 3, 4]


In [11]:
# Ver el tipo de dato de la lista.
type(my_list)

list

## 🔄 Arreglos

In [4]:
# Creación de un array a partir de una lista.
my_array = np.array([1, 2, 3, 4])
print(my_array)

[1 2 3 4]


In [6]:
# Comprobación del tipo de dato. El tipo de dato es numpy.ndarray, el cual es un array de numpy.
type(my_array)

numpy.ndarray

In [7]:
# Multiplicación de un array por un escalar. El resultado es un array con los elementos multiplicados.
my_array * 2

array([2, 4, 6, 8])

## 🧮 Matrices

In [9]:
matriz_a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [10]:
matriz_a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
matriz_b = np.array([[2, 3, 4], [5, 10, 4], [1, 1, 1]])

In [13]:
matriz_b

array([[ 2,  3,  4],
       [ 5, 10,  4],
       [ 1,  1,  1]])

### Operaciones con matrices

#### Suma algebraica

> 📝 **Nota**
>
> Es importante recordar que para efectuar una suma algebraica de matrices, estas deben ser de la misma dimensión.

In [14]:
# Suma de matrices.
suma = matriz_a + matriz_b
suma

array([[ 3,  5,  7],
       [ 9, 15, 10],
       [ 8,  9, 10]])

In [15]:
# Resta de matrices.
resta = matriz_a - matriz_b
resta

array([[-1, -1, -1],
       [-1, -5,  2],
       [ 6,  7,  8]])

In [20]:
# Otra forma de hacer la suma de matrices.
suma_fn = np.add(matriz_a, matriz_b)
print(suma_fn)

[[ 3  5  7]
 [ 9 15 10]
 [ 8  9 10]]


In [21]:
# Otra forma de hacer la resta de matrices.
resta_fn = np.subtract(matriz_a, matriz_b)
print(resta_fn)

[[-1 -1 -1]
 [-1 -5  2]
 [ 6  7  8]]


#### Multiplicación

La multiplicación de matrices es una operación que se puede realizar entre dos matrices siempre y cuando el número de **columnas** de la primera matriz coincida con el número de **filas** de la segunda matriz.

Formas de multiplicar matrices:
- `*`: Se multiplican los elementos de la matriz de la izquierda por los de la derecha.
- `np.multiply()`: Se multiplican los elementos de la matriz de la izquierda por los de la derecha (elemento a elemento, como el operador `*`).
- `@`: Se multiplican las matrices de forma algebraica.
- `np.dot()`: Se multiplican las matrices de forma algebraica.


In [22]:
# Multiplicación de matrices con el operador *.
multiplicacion = matriz_a * matriz_b
multiplicacion

array([[ 2,  6, 12],
       [20, 50, 24],
       [ 7,  8,  9]])

In [23]:
# Multiplicación de matrices con la función np.multiply().
multiplicacion_fn = np.multiply(matriz_a, matriz_b)
print(multiplicacion_fn)

[[ 2  6 12]
 [20 50 24]
 [ 7  8  9]]


In [24]:
# Multiplicación de matrices con la función np.dot().
multiplicacion_dot = np.dot(matriz_a, matriz_b)
print(multiplicacion_dot)

[[ 15  26  15]
 [ 39  68  42]
 [ 63 110  69]]


In [25]:
# Multiplicación de matrices con el operador @.
multiplicacion_arroba = matriz_a @ matriz_b
print(multiplicacion_arroba)

[[ 15  26  15]
 [ 39  68  42]
 [ 63 110  69]]


In [26]:
# Si se intenta multiplicar un vector por una matriz, se obtiene un error:
vector = np.array([1, 2, 3, 4])
vector @ matriz_a

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)

### Transpuesta

Para transponer una matriz utilizando la librería `numpy` se utiliza el operador `.T`.

In [27]:
matriz_a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

# 📅 2023-11-08

## 🔢 `arange()`

La función `arange()` de la librería `numpy` permite crear un arreglo de números enteros en un rango determinado.

In [3]:
# Generar un arreglo vector del 0 al 10 con pasos de 2 en 2.
np.arange(0, 10, 2, dtype = float)

array([0., 2., 4., 6., 8.])

## 👋🏽 `01101000 01101111 01101100 01100001`

### Ceros

In [5]:
# Generar un arreglo de cinco ceros, de tipo entero.
np.zeros(5, dtype = int)

array([0, 0, 0, 0, 0])

In [6]:
# Generar una matriz de 3x3 de ceros, de tipo entero.
np.zeros((3, 3), dtype = int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [7]:
# Vector de seis ceros.
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [8]:
# Matriz de 1x6 de ceros.
np.zeros((1, 6))

array([[0., 0., 0., 0., 0., 0.]])

In [9]:
# Matriz de 1x6 de unos.
np.ones((1, 6))

array([[1., 1., 1., 1., 1., 1.]])

# 📅 2023-11-09

## 🕐 Repaso 2023-11-08

In [10]:
# Generar arreglo de una dimensión (vector), con un rango del 0 al 10 y con pasos de 3 en 3.
np.arange(0, 10, 3)

array([0, 3, 6, 9])

In [11]:
# Generar un vector de 5 elementos, los cuales son ceros y de tipo entero.
np.zeros(5, dtype = int)

array([0, 0, 0, 0, 0])

In [12]:
# Generar una matriz de ceros de orden 3x3.
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
# Generar un vector de 5 elementos, los cuales son unos y de tipo entero.
np.ones(5, dtype = int)

array([1, 1, 1, 1, 1])

In [14]:
# Generar una matriz de unos de orden 4x3. Su tipo es entero.
np.ones((4,3), dtype = int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

## 📏 `linspace()`

In [15]:
# Generar arreglo vector espaciado linealmente cinco vecces.
# «5 elementos espaciados entre si para llegar al diez».
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

⚠️ *Aquí, el stop si es **inclusivo**, a diferencia del np.arange()*

## 🧿 Matriz identidad

In [16]:
# Generar matriz identidad de 4x4.
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## 🎲 random.rand(d<sub>n</sub>), random.randn(d<sub>n</sub>) y random.randint(d<sub>n</sub>)

### rand

La función `random.rand()` permite crear un arreglo de números aleatorios del 0 al 1 con una dimensión d<sub>n</sub>.

In [17]:
np.random.rand(5)

array([0.90095731, 0.93749815, 0.20692717, 0.11487035, 0.07595225])

In [18]:
# Generar un arreglo matriz con valores aleatorios del 0 al 1.
np.random.rand(3, 3)

array([[0.00600918, 0.17003795, 0.1676597 ],
       [0.70491988, 0.22775182, 0.4178018 ],
       [0.89352839, 0.36562743, 0.32489971]])

### randn

La función `random.randn()` permite crear un arreglo de números aleatorios con una distribución normal.

In [19]:
np.random.randn(5)

array([-0.2060831 ,  0.18907521,  0.29792029,  0.34073228, -1.63545136])

![Distribución Gaussiana Normal](https://www.sharpsightlabs.com/wp-content/uploads/2020/09/numpy-random-randn_featured-image.png)

In [20]:
# Generar un arreglo matriz con valores de una distribución Gaussiana Normal. De 3x3 y con solo dos decimales.
np.round(np.random.randn(3, 3), 2)

array([[ 0.13,  0.64,  0.18],
       [-0.24,  0.83,  0.87],
       [-0.89, -0.31,  0.83]])

### randint

In [22]:
# Generar un arreglo vector de tres números aleatorios del 0 al 100 (excluyendo el 100).
np.random.randint(0, 100, 3)

array([15, 72, 89])

In [23]:
# Generar un arreglo matriz de 3x3 con valores aleatorios del 0 al 100.
np.random.randint(0, 100, (3, 3))

array([[70, 49, 40],
       [35, 41, 54],
       [99, 43, 95]])

## 🌱 Semilla

Una semilla es un número que se utiliza para generar números aleatorios. Esto es útil para poder generar los mismos números aleatorios en diferentes ejecuciones de un programa.

In [24]:
np.random.seed(42)
np.random.rand(5)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864])

In [25]:
np.random.rand(5)

array([0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258])

In [26]:
# Se obtienen los mismos valores que antes, pues se utiliza la misma semilla de reproducibilidad.
np.random.seed(42)
np.random.rand(5)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864])

## 👨🏽‍💻 Ejercicios

### 1. Semilla para un randn (vector).

In [27]:
np.random.seed(42)
np.random.randn(5)

array([ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986, -0.23415337])

### 2. Semilla para un randn (matriz).

In [28]:
np.random.seed(42)
np.random.randn(3, 3)

array([[ 0.49671415, -0.1382643 ,  0.64768854],
       [ 1.52302986, -0.23415337, -0.23413696],
       [ 1.57921282,  0.76743473, -0.46947439]])

### 3. Semilla para un randint (vector).

In [29]:
np.random.seed(42)
np.random.randint(0, 50, 5)

array([38, 28, 14, 42,  7])

### 4. Semilla para un randint (matriz).

In [30]:
np.random.seed(42)
np.random.randint(0, 50, (3,3))

array([[38, 28, 14],
       [42,  7, 20],
       [38, 18, 22]])

# 📅 2023-11-13

## 🕑 Repaso 2023-11-09

In [31]:
# linspace: Se genera un arreglo vector de 4 elementos, que van del 0 al 100.
np.linspace(0, 100, 4)

array([  0.        ,  33.33333333,  66.66666667, 100.        ])

In [32]:
# rand: Se genera un arreglo matriz de 3x3, con valores aleatorios del 0 al 1.
np.random.rand(3, 3)

array([[0.05808361, 0.86617615, 0.60111501],
       [0.70807258, 0.02058449, 0.96990985],
       [0.83244264, 0.21233911, 0.18182497]])

In [33]:
# randn: Se genera un arreglo matriz de 3x3, con valores aleatorios de una distribución Gaussiana Normal.
np.random.randn(3, 3)

array([[-0.57138017, -0.92408284, -2.61254901],
       [ 0.95036968,  0.81644508, -1.523876  ],
       [-0.42804606, -0.74240684, -0.7033438 ]])

In [34]:
# randn: Se genera un arreglo vector de 5 elementos, con valores aleatorios de una distribución Gaussiana Normal.
np.random.randn(5)

array([-2.13962066, -0.62947496,  0.59772047,  2.55948803,  0.39423302])

In [35]:
# randint: Se genera una matriz de 3x3, con valores aleatorios del 1 al 99 (porque el 100 es excluyente).
np.random.randint(1, 100, (3,3))

array([[ 3, 51,  7],
       [21, 73, 39],
       [18,  4, 89]])

In [36]:
# seed: Una semilla de reproducibilidad permite obtener los mismos valores aleatorios. Funciona con rand, randn y randint.
np.random.seed(42)
np.random.rand(5)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864])

## 🌀 .`reshape()`: Una función para cambiar la forma de un arreglo.

In [39]:
# Generar un arreglo con elementos del 0 al 50, con pasos de 2 en 2.
array = np.arange(0, 50, 2)

In [40]:
array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

*El arreglo resultante es de 25 elementos.*

In [41]:
# Consultar la actual forma del arreglo.
array.shape

(25,)

In [42]:
# Cambiar la forma del arreglo a una matriz de 5x5.
array.reshape(5, 5)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48]])

## 📊 Máximo, mínimo, suma, promedio e índices del máximo y mínimo.

In [43]:
# Generar un arreglo vector de 10 elementos, que van de 0 a 99.
rand_array = np.random.randint(0, 100, 10)
rand_array

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [44]:
# Obtener su máximo.
rand_array.max()

99

In [45]:
# Obtener su mínimo.
rand_array.min()

2

In [46]:
# Obtener su suma.
rand_array.sum()

600

In [47]:
# Obtener su promedio.
rand_array.mean()

60.0

In [48]:
# Obtener su argumento máximo (índice del máximo valor).
rand_array.argmax()

5

In [49]:
# Obtener su argumento mínimo (índice del mínimo valor).
rand_array.argmin()

7

# 📅 2023-11-14

## 🕑 Repaso 2023-11-13

### 🧩 Reestructuración de un arreglo: `.reshape()`.

In [2]:
import numpy as np

In [ ]:
# Crear un array de 0 a 24.
array = np.arange(0, 25)

In [ ]:
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
# Convertir el array en una matriz de 5x5.
array.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
# Convertir el array en una matriz de 25x1.
array.reshape(25, 1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [ ]:
# Volverlo a su estado original.
array.reshape(1, 25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

### 📊 Máximo, mínimo, suma, promedio e índices del máximo y mínimo.

In [3]:
# Crear un array de 25 números aleatorios enteros entre 0 y 100.
array2 = np.random.randint(0, 100, 25)

In [4]:
array2

array([37, 34, 62, 80, 33, 20, 45, 68, 49,  2,  5, 23, 94, 63, 85, 56, 11,
       25, 17, 47, 92, 79, 32, 33, 12])

In [5]:
array2.max()

94

In [6]:
array2.min()

2

In [7]:
array2.sum()

1104

In [8]:
array2.mean()

44.16

In [9]:
array2.argmax()

12

In [10]:
array2.argmin()

9

## 🔎 Consultar elementos

In [11]:
array2[5]

20

In [12]:
array2

array([37, 34, 62, 80, 33, 20, 45, 68, 49,  2,  5, 23, 94, 63, 85, 56, 11,
       25, 17, 47, 92, 79, 32, 33, 12])

In [13]:
# Slice del 5 al 10:
array2[5: 10]

array([20, 45, 68, 49,  2])

In [14]:
array3 = np.arange(0, 20)

In [15]:
array3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [16]:
array3[3]

3

In [17]:
# Consultar los primeros 10 elementos.
array3[:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
# Consultar los primeros 5 elementos.
array3[:5]

array([0, 1, 2, 3, 4])

In [19]:
# Hacer un broadcast para convertir a 100 ciertos índices.
array3[0:5] = 100

In [20]:
array3

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

In [21]:
# El copy() es más rápido para hacer copias de arreglos.
array_copy = array3.copy()

In [22]:
array_copy

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

In [23]:
array_copy.reshape(4, 5)

array([[100, 100, 100, 100, 100],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19]])

In [24]:
array_copy.sum()

680

In [25]:
array_copy.mean()

34.0

In [26]:
array_copy.min()

5

In [27]:
array_copy.max()

100

# 📅 2023-11-16

## 🔎 Más sobre la consulta de elementos

In [28]:
arr2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])
arr2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [29]:
# ¿Cómo ver el primer renglón del arreglo de dos dimensiones?
arr2d[0]

array([ 5, 10, 15])

In [30]:
# Segundo renglón.
arr2d[1]

array([20, 25, 30])

In [31]:
# Tercer renglón.
arr2d[2]

array([35, 40, 45])

In [32]:
# Visualizar el 25.
arr2d[1, 1]

25

In [33]:
# Ver los dos primeros renglones.
arr2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [34]:
# Mostrar solamente el 5, 10, 20, 25, 35 y 40.
arr2d[0:3, 0:2]

array([[ 5, 10],
       [20, 25],
       [35, 40]])

In [35]:
# Mostrar solamente el 10, 15, 25 y 30.
arr2d[0:2, 1:]

array([[10, 15],
       [25, 30]])

In [36]:
# Mostrar solamente el 20, 25, 35 y 40.
arr2d[1:3, 0:2]

array([[20, 25],
       [35, 40]])

## 📊 Más operaciones con arreglos

In [37]:
# Generar un arreglo de una dimensión.
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
# Broadcast: Sumar 5 a cada elemento del arreglo.
arr + 5

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [39]:
# Multiplicar por 3 a cada elemento del arreglo.
arr * 3

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [40]:
# Validar si cada elemento es mayor que 4.
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [41]:
# Agregar un nuevo elemento al arreglo.
nuevo_elemento = 100
np.append(arr, nuevo_elemento)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10, 100])

In [42]:
# Validar cuáles elementos resultan verdaderos al compararlos con 4.
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])

In [43]:
# Dividir cada elemento del arreglo entre 2.
arr / 2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [44]:
# Sumatoria de todos los elementos del arreglo.
arr.sum()

55

In [45]:
# Multiplicación de todos los elementos del arreglo.
arr.prod()

3628800

In [46]:
# Promedio de todos los elementos del arreglo.
arr.mean()

5.5

In [47]:
# Argumento del máximo elemento del arreglo.
arr.argmax()

9

In [48]:
# Argumento del mínimo elemento del arreglo.
arr.argmin()

0

In [49]:
# Desviación estándar del arreglo.
arr.std()

2.8722813232690143

In [51]:
# Varianza del arreglo.
arr.var()

8.25

In [52]:
# Raíz cuadrada de todos los elementos del arreglo.
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [53]:
# Seno de todos los elementos del arreglo.
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [54]:
# Coseno de todos los elementos del arreglo.
np.cos(arr)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029,  0.75390225, -0.14550003, -0.91113026, -0.83907153])

In [55]:
# Logaritmo natural de todos los elementos del arreglo.
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [56]:
# Generar un vector aleatorio de 25 elementos, del 0 al 100.
vector = np.random.randint(0, 100, 25)
vector

array([22, 41, 35, 47, 18, 62, 60, 34, 70, 56, 61, 58, 17, 46, 23, 14, 47,
       66, 89, 70, 60, 29, 16, 16, 61])

In [57]:
vector_re = vector.reshape(5, 5)
vector_re

array([[22, 41, 35, 47, 18],
       [62, 60, 34, 70, 56],
       [61, 58, 17, 46, 23],
       [14, 47, 66, 89, 70],
       [60, 29, 16, 16, 61]])

In [58]:
# Sumar cada uno de los renglones.
# axis = 0: Sumar por renglones.
vector_re.sum(axis = 0)

array([219, 235, 168, 268, 228])

In [59]:
# Sumar cada uno de los columnas.
# axis = 0: Sumar por columnas.
vector_re.sum(axis = 1)

array([163, 282, 205, 286, 182])