In [1]:
import numpy as np

## 1️⃣ First Part

**Check-In: Operations on NumPy Array**

Let's check in with you to make sure you've understood the previous exercises.
Make sure to read the instructions carefully!

**Coding Exercise Check-In: Operations on NumPy Array**

*TASK:* A bank account has had withdrawals and deposits tracked in a numpy array called `account_transactions`. Based on this list of account transactions,
- What is the total remaining in the account?
- Assign your answer to a variable called `account_total`.
- Please note, in order for the exercise to evaluate correctly, you must use the **variable** name `account_total`.

In [10]:
account_transactions = np.array([100, -200, 300, -400, 100, 100, -230, 450, 500, 2000])
account_total = account_transactions.sum()
print("Account Total: ", account_total)

Account Total:  2720


## 2️⃣ Second Part 

### NumPy Exercises

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks and then you'll be asked some more complicated questions.

<div class="alert alert-danger" style="margin: 10px"><strong>IMPORTANT NOTE!</strong> Make sure you don't run the cells directly above the example output shown, <br>otherwise you will end up writing over the example output!</div>

#### 1. Import NumPy as np

In [3]:
import numpy as np

#### 2. Create an array of 10 zeros 

In [4]:
# CODE HERE
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
# DON'T WRITE HERE

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 3. Create an array of 10 ones

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
# DON'T WRITE HERE

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### 4. Create an array of 10 fives

In [6]:
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [ ]:
# DON'T WRITE HERE

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### 5. Create an array of the integers from 10 to 50

In [7]:
np.arange(10, 51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [ ]:
# DON'T WRITE HERE

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### 6. Create an array of all the even integers from 10 to 50

In [8]:
np.arange(10, 51, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [ ]:
# DON'T WRITE HERE

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### 7. Create a 3x3 matrix with values ranging from 0 to 8

In [9]:
np.arange(0, 9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
# DON'T WRITE HERE

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])