In [1]:
import numpy as np

$$
A = \begin{bmatrix}
5 & 6 & 9 \\
10 & 15 & 20 \\
16 & 21 & 14
\end{bmatrix}
B = \begin{bmatrix}
7 & 2 & 6 \\
2 & 5 & 10 \\
1 & 1 & 1 \\
10 & 10 & 10
\end{bmatrix}
$$

In [3]:
A = np.array([[5, 6, 9], [10, 15, 20], [16, 21, 14]])
print("Matriz A: \n", A)
print("\n")
B = np.array([[7, 2, 6], [2, 5, 10], [1, 1, 1], [10, 10, 10]])
print("Matriz B: \n", B)

Matriz A: 
 [[ 5  6  9]
 [10 15 20]
 [16 21 14]]


Matriz B: 
 [[ 7  2  6]
 [ 2  5 10]
 [ 1  1  1]
 [10 10 10]]


C = Es un vector generado por la función arange(2, 14). Sin incluir el 14.

In [15]:
C = np.arange(2, 14)
print("Vector C: \n", C)

Vector C: 
 [ 2  3  4  5  6  7  8  9 10 11 12 13]


D = Es el vector C convertido a matriz de orden (3, 4).

In [5]:
D = C.reshape(3, 4)
print("Matriz D: \n", D)

Matriz D: 
 [[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]


E = D<sub>T</sub>

In [6]:
E = D.T
print("Matriz E: \n", E)

Matriz E: 
 [[ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]
 [ 5  9 13]]


Y = Matriz de puros «unos» de orden (3, 4).

In [7]:
Y = np.ones((3, 4))
print("Matriz Y: \n", Y)

Matriz Y: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


v = [1, 2 , 3]

In [13]:
v = np.array([1, 2, 3])
print("Vector v: \n", v)

Vector v: 
 [1 2 3]


In [9]:
# 1. Obtener el valor de X, X = (B * A) + E.
X = (B @ A) + E
print("Matriz X: \n", X)

Matriz X: 
 [[153 204 197]
 [223 304 269]
 [ 35  50  55]
 [315 429 443]]


In [16]:
# 2. El valor mínimo, máximo, la sumatoria, el promedio, argmax y argmin de la matriz X.
print("Máximo: ", np.max(X))
print("Mínimo: ", np.min(X))
print("Sumatoria: ", np.sum(X))
print("Promedio: ", np.mean(X))
print("Argmax: ", np.argmax(X))
print("Argmin: ", np.argmin(X))

Máximo:  443
Mínimo:  35
Sumatoria:  2677
Promedio:  223.08333333333334
Argmax:  11
Argmin:  6


In [12]:
# 3. Obtener el valor de R, R = X * Y.
R = X @ Y
print("Matriz R: \n", R)

Matriz R: 
 [[ 554.  554.  554.  554.]
 [ 796.  796.  796.  796.]
 [ 140.  140.  140.  140.]
 [1187. 1187. 1187. 1187.]]


In [14]:
# 4. Obtener el valor de S, S = R * v.
S = R @ v

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)

*El error anterior se debe a que el numero de columnas de la primer matriz 🚨NO🚨 es igual al numero de filas del vector (4 no es igual a 3).*